// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkPGEiIo4laipL75I7U3bthxj_7EzJkIQ',
    appId: '1:484665697344:web:efce485ea84b47989b6ba5',
    messagingSenderId: '484665697344',
    projectId: 'demo1-6b12c',
    authDomain: 'demo1-6b12c.firebaseapp.com',
    storageBucket: 'demo1-6b12c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDizZ0yrwU8BrZ7efqRSA87aV3b7NvaREo',
    appId: '1:484665697344:android:664410ebf89d9f509b6ba5',
    messagingSenderId: '484665697344',
    projectId: 'demo1-6b12c',
    storageBucket: 'demo1-6b12c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZf1DIrUFTvjWRAAZouUNsFYYKrKqAg0',
    appId: '1:484665697344:ios:5670977b523db0129b6ba5',
    messagingSenderId: '484665697344',
    projectId: 'demo1-6b12c',
    storageBucket: 'demo1-6b12c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpZf1DIrUFTvjWRAAZouUNsFYYKrKqAg0',
    appId: '1:484665697344:ios:5670977b523db0129b6ba5',
    messagingSenderId: '484665697344',
    projectId: 'demo1-6b12c',
    storageBucket: 'demo1-6b12c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkPGEiIo4laipL75I7U3bthxj_7EzJkIQ',
    appId: '1:484665697344:web:507dd911c78b445b9b6ba5',
    messagingSenderId: '484665697344',
    projectId: 'demo1-6b12c',
    authDomain: 'demo1-6b12c.firebaseapp.com',
    storageBucket: 'demo1-6b12c.firebasestorage.app',
  );
}
